[package]
name = "blake2b-cell-data-cycle-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-testtool = "0.10.0"
rand = "0.8.5"
